baseURL: 'https://www.manuelroemer.com/'
languageCode: 'en'
title: "Manu's Site"

# Hugo's default title pluralization leads to weird titles. -> Disabled for now.
pluralizeListTitles: false

frontmatter:
  # `date` and `publishDate` should have the same meaning.
  # See the README for details.
  date:
    - date
    - publishDate
  publishDate:
    - date
    - publishDate

  # `lastmod` should indicate an explicit edit/update to a page.
  # A page should only appear as edited, if `lastmod` is explicitly set.
  # See the README for details.
  lastmod: ['lastmod']

menu:
  # The main menu contained in the page's navigation bar.
  main:
    - identifier: 'blog'
      name: 'Blog'
      url: '/blog'

  # The "Legal" menu in the footer.
  legal:
    - identifier: 'imprint'
      name: 'Impressum'
      url: '/impressum'
    - identifier: 'privacyPolicy'
      name: 'Privacy Policy'
      url: '/privacy'

params:
  # Shared formatting templates that are used in various locations.
  fmt:
    date: '02.01.2006'
    dateTime: '02.01.2006 15:04:05'
    dateISO: '2006-01-02T15:04:05-07:00'

  # The copyright notice to be shown in the footer.
  copyright: '&copy; 2022 Manuel Römer. Made with ♥ in 🇩🇪.'

  # Social connections/links rendered in the footer.
  # Each social connection is rendered as an image.
  # Image variants need to be provided for both a light and dark mode.
  socialConnections:
    - name: 'GitHub'
      link: 'https://github.com/manuelroemer'
      imgSrcLight: 'images/github-logo-light.png'
      imgSrcDark: 'images/github-logo-dark.png'
    - name: 'LinkedIn'
      link: 'https://www.linkedin.com/in/manuel-roemer'
      imgSrcLight: 'images/linkedin-logo-light.png'
      imgSrcDark: 'images/linkedin-logo-dark.png'
