baseURL: 'https://www.manuelroemer.com/'
languageCode: 'en'
title: "Manu's Site"

# Hugo's default title pluralization leads to weird titles. -> Disabled for now.
pluralizeListTitles: false

# Auto-generate the page's main menu from sections.
# If necessary later, this can be converted to a manually managed menu later.
sectionPagesMenu: 'main'

menu:
  # The main menu contained in the page's navigation bar.
  main:
    - identifier: 'blog'
      name: 'Blog'
      url: '/blog'

  # The "Legal" menu in the footer.
  legal:
    - identifier: 'imprint'
      name: 'Impressum'
      url: '/impressum'
    - identifier: 'privacyPolicy'
      name: 'Privacy Policy'
      url: '/privacy'

params:
  fmt:
    date: '02.01.2006'
    dateTime: '02.01.2006 15:04:05'
    dateISO: '2006-01-02T15:04:05-07:00'

  # The copyright notice to be shown in the footer.
  copyright: '&copy; 2022 Manuel Römer. Made with ♥ in 🇩🇪.'

  # Social connections/links rendered in the footer.
  # These are rendered as images. Variants need to be provided for light and dark modes.
  socialConnections:
    - name: 'GitHub'
      link: 'https://github.com/manuelroemer'
      imgSrcLight: 'images/github-logo-light.png'
      imgSrcDark: 'images/github-logo-dark.png'
    - name: 'LinkedIn'
      link: 'https://www.linkedin.com/in/manuel-roemer'
      imgSrcLight: 'images/linkedin-logo-light.png'
      imgSrcDark: 'images/linkedin-logo-dark.png'
